// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyqecnyzyzeuhygbrjzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5cWVjbnl6eXpldWh5Z2JyanpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mzc0NzIsImV4cCI6MjA2NTUxMzQ3Mn0.DVLo6iuPsLgCOgibTDz8ocwLlrjAhvW8eGjYVeUAFAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);